services:
  - type: web
    name: be-todo-02240334
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./todo-app/backend/Dockerfile
    dockerContext: ./todo-app/backend
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false

  - type: web
    name: fe-todo-02240334
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./todo-app/frontend/Dockerfile
    dockerContext: ./todo-app/frontend
    envVars:
      - key: VITE_API_URL
        value: https://be-todo-02240334.onrender.com